= Changelog

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

== link:++https://gilbert.informatik.uni-stuttgart.de/enpro-ws2019-20/enpro-livingdoc/compare/b81fe455...master++[Unreleased]

=== Added

- Changelog to document changes between versions
- The Livingdoc configuration can be specified via Java System Properties
- Repository to load data from a webserver
- Confluence Document Repository to load Examples from Confluence
- Annotation to disable documents and fixtures
- Test Reports can be configured in the `livingdoc.yml`
- Test Reports in JSON format
- Custom Test Report formats can be added and used via Java SPI
- Add manual test annotation to markdown and HTML documents so the test will not be executed by junit but appear in the reports as manually executed
- Add possibility to specify a confluence document version
- Exceptions as expected output can be specified in the Examples with the keyword "error"
- Add converter to convert colors
- A `@Group` annotation that can be used to group `@ExecutableDocument` classes

=== Changed

- DecisionTables and Scenarios without a matching fixture will now
  generate an exception instead of being silently ignored.
- Updated to gradle version 5.6.4
- `@Before` and `@After` annotations can now also be used on methods inside classes annotated with `@ExecutableDocument`
