build:
  maxIssues: 0

complexity:
  TooManyFunctions:
    ignorePrivate: true

exceptions:
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - Throwable

style:
  ForbiddenComment:
    active: false
  ThrowsCount:
    active: false

